services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
    restart: always
    depends_on:
      ollama:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"  # Cambiado el puerto para evitar conflicto
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    restart: always

  ollama:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD", "curl", "-f", "http://ollama:port/health"]
      interval: 30s
      timeout: 10s
      retries: 5